### ISSUE TITLE
No class de found error

### ISSUE THREAD

**Issue by MathisSkateMC** [simon816/SpongeBootstrap#17]
Hello i have this problem

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
        at com.simon816.sponge.bootstrap.Bootstrap.<clinit>(Bootstrap.java:32)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 1 more
        
This build works for 1.16.5 ?

**Comment by simon816** [comment]
I can confirm the crash, however I'm surprised if this is needed for 1.16.5

**Comment by simon816** [comment]
In fact, I've just looked at forge 1.16.5 and it's completely different so SpongeBootstrap wouldn't work anyway.

I'll close this for now. If there's a mod which you think requires SpongeBootstrap then I can take a look.
