### ISSUE TITLE
Compatibility: 1.11.2

### ISSUE THREAD

**Issue by axle2005** [simon816/SpongeBootstrap#4]
Trying to get ahead of the curve here, as the FTB team is discussing moving to 1.11.2 in the near future and we heavily use this because of AE2. 

I see in the build.gradle 1.11 is supported, although everytime I try to load up a just a vanilla server using one of the experimental versions of 1.11.2 sponge forge and it is constantly throwing: 

I've reinstalled the forge environment a few times and can even load the server if I am not using the Bootstrap. 

Any help would be appreciated. 

Forge: forge-1.11.2-13.20.0.2259-universal
SpongeForge:  spongeforge-1.11.2-2227-6.0.0-BETA-2232
Minecraft: 1.11.2

`
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
        at com.simon816.sponge.bootstrap.Bootstrap.<clinit>(Bootstrap.java:32)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 1 more`

**Comment by simon816** [comment]
Ah yes I see, need to add `1.11.2` to the classpath, I'll fix that

**Comment by simon816** [comment]
Couldn't find a 1.11.2 version of AE2 to test this with, but should work
